apiVersion: batch/v1
kind: Job
metadata:
  annotations:
    argocd.argoproj.io/hook: PreSync
    argocd.argoproj.io/sync-options: Prune=true
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"batch/v1","kind":"Job","metadata":{"annotations":{"argocd.argoproj.io/hook":"PostSync","argocd.argoproj.io/hook-delete-policy":"HookSucceeded"},"name":"nebula-api-callafter","namespace":"default"},"spec":{"backoffLimit":0,"template":{"spec":{"containers":[{"command":["curl","http://nebula:8000/api/v1/k8s"],"image":"alpine:latest","name":"sleep"}],"restartPolicy":"Never"}}}}
  name: nebula-api-callafter
  namespace: default
spec:
  backoffLimit: 0
  template:
    spec:
      containers:
      - command:
        - curl
        - http://192.168.2.84:8000/api/v1/k8s
        image: byrnedo/alpine-curl
        name: neubla
      restartPolicy: Never
